from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from mgm8.domain.models import AntennaPosition, OperationalEvent, ScheduledPass, SchedulingConflict


class ScheduledPassRepository(Protocol):
    def get_active_in_window(self, start: datetime, end: datetime) -> list[ScheduledPass]: ...
    def add(self, scheduled_pass: ScheduledPass) -> None: ...


class SchedulingConflictRepository(Protocol):
    def add(self, conflict: SchedulingConflict) -> None: ...


class OperationalEventRepository(Protocol):
    def add(self, event: OperationalEvent) -> None: ...


class RotorPort(Protocol):
    """Porta de saída: comanda o rotor físico (ou um substituto de testes)."""

    def move_to(self, position: AntennaPosition) -> None: ...
    def read_position(self) -> AntennaPosition: ...
    def stop(self) -> None: ...
    def park(self) -> None: ...


class RotorControlUseCase(Protocol):
    """Porta de entrada: casos de uso expostos ao adapter rotctld."""

    def set_target(self, azimuth_degrees: float, elevation_degrees: float) -> AntennaPosition: ...
    def get_position(self) -> AntennaPosition: ...
    def stop(self) -> None: ...
    def park(self) -> None: ...
